services:
  mssql-server:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: mssql-server
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
      MSSQL_SA_PASSWORD: "msProj2025"
    ports:
      - "2433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

  adminer:
    image: adminer:4.8.1
    container_name: adminer
    ports:
      - 2431:8080
    environment:
      TZ: Europe/Rome
      ADMINER_DEFAULT_SERVER: mssql-server

  kafka:
    image: 'bitnami/kafka:3.1.0'
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  zookeeper:
    image: 'bitnami/zookeeper:3.9.0'
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  orders-api:
    image: ghcr.io/danieletallo/orders-api:latest
    container_name: ecomm-orders-api
    depends_on:
      - mssql-server
      - kafka
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      TZ: Europe/Rome
    ports:
      - "5000:80"

  payments-api:
    image: ghcr.io/danieletallo/payments-api:latest
    container_name: ecomm-payments-api
    depends_on:
      - mssql-server
      - kafka
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      TZ: Europe/Rome
    ports:
      - "5001:80"

  register-api:
    image: ghcr.io/danieletallo/registry-api:latest
    container_name: ecomm-registry-api
    depends_on:
      - mssql-server
      - kafka
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      TZ: Europe/Rome
    ports:
      - "5002:80"

  warehouse-api:
    image: ghcr.io/danieletallo/warehouse-api:latest
    container_name: ecomm-warehouse-api
    depends_on:
      - mssql-server
      - kafka
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      TZ: Europe/Rome
    ports:
      - "5003:80"

volumes:
  mssql-data:
